= Java MVC Done Many Ways

Deplying an MVC web app as "manually" as possible. +

Started by generating a creating a simple servlet, packaging it into a 
WAR file with Gradle, then copying it into the ``webapp`` directory on 
a locally running Tomcat server. +

IMPORTANT: `@EnableWebMvc` is a required annotation for your configuration class if you 
want object-mapping on your controllers.  

The config classes are where you set `@ComponentScan` so you don't have to register the 
beans yourself. Every context has it's own config file, i.e. it's own set of beans. 
You can distinguish shared _root_ contexts from isolated _servlet_, or app-level contexts.  

IMPORTANT: `@RequestMapping` value attribute is taken literally when it matches the dispatcher mapping, 
otherwise the path is appended to the dispatcher mapping. E.g. `@RequestMapping(value = "/video/health")` 
maps to `/video/video/health`, where `/video` is the dispatcher mapping. 


IMPORTANT: Remember that if your controllers are serving `ViewResolver`s, to _not_ use the `@RestController` 
annotation. This annotation implicitly uses `@ResponseBody` which automatically serializes the response to JSON.


If testing Controllers with `MockMvc.standaloneSetup`, make sure the `javax.servlet-api` dependency is available during 
runtime, not just compile time. Otherwise you may get a `ClassDefNotFound` exception when the method tries to find the 
controller(s) you pass as an argument.
